### ISSUE TITLE
How to run the script?

### ISSUE THREAD

**Issue by jagarop** [matthewlilley/escape-from-tarkov#2]
Hello, how i can run the script after download and npm install?

![image](https://user-images.githubusercontent.com/8181801/75272536-e1be7b00-57dc-11ea-842e-614f226e6897.png)

**Comment by matthewlilley** [comment]
Rename the config.example.json in the examples folder to config.json, add your credentials and add a storage path, and then npm run examples:worker.

**Comment by matthewlilley** [comment]
Updated readme with directions for those that need it.
